version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\openclonk
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cd C:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install glew:x64-windows freetype:x64-windows freeglut:x64-windows libjpeg-turbo:x64-windows bzip2:x64-windows zlib:x64-windows libpng:x64-windows sdl2:x64-windows

before_build:
- cmd: >-

    cd c:\projects\openclonk\
    
    mkdir build
    
    cd build
    
    cmake --version
    
    cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G %generator% ..
    
build:
  project: c:\projects\openclonk\build\openclonk.sln
  verbosity: minimal
  parallel: true 
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - include/
    - tests/
    - cmake/