version: '{build}'
branches:
  only:
  - master
shallow_clone: true
clone_folder: c:\projects\openclonk

image:
- Visual Studio 2017
platform:
  - x64
configuration: RelWithDebInfo
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true
  
artifacts:
  - path: openclonk-windows-amd64.zip
    name: build planet

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

install:
  - cd C:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install glew:x64-windows freetype:x64-windows freeglut:x64-windows libjpeg-turbo:x64-windows bzip2:x64-windows zlib:x64-windows libpng:x64-windows sdl2:x64-windows
  
cache: c:\tools\vcpkg\

before_build:
- cmd: >-

    cd c:\projects\openclonk\
    
    mkdir build
    
    cd build
    
    cmake --version
    
    cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G %generator% ..
    
build:
  project: c:\projects\openclonk\build\openclonk.sln
  verbosity: minimal
  parallel: true 
 
after_build:
  - ps: Push-AppveyorArtifact openclonk-windows-amd64.zip
  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - include/
    - tests/
    - cmake/